name = "Moss Client"
author = "Lucaslah"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc1a4f188c034173cc8869549f3177f7d058e6b74276c0e0809a16d590aa1865"

[versions]
minecraft = "1.20.4"
quilt = "0.23.0"

[options]
acceptable-game-versions = ["1.20.1", "1.20.2", "1.20.3"]
