name: Build

on:
  push:
    branches-ignore:
        - master

jobs:
  build-mrpack:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup build number
        run: echo "BUILD_NUMBER=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Update version
        run: |
          current_version=$(grep -E '^version\s*=' pack/pack.toml | awk -F\" '{print $2}')
          new_version=$BUILD_NUMBER
          sed -i "s/^version\s*=\s*\"$current_version\"/version = \"$new_version\"/" pack/pack.toml
      - name: Build MrPack
        run: |
          chmod +x ./scripts/ci/build.sh
          ./scripts/ci/build.sh
      - name: Upload Build Results
        uses: actions/upload-artifact@v3
        with:
          name: MossClient-MrPack
          path: build/*.mrpack

  build-modlist:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Modlist
        shell: pwsh
        run: |
          $env:TEMP = "/tmp"
          ./scripts/Moss.ps1 build mod-list
      - name: Upload Build Results
        uses: actions/upload-artifact@v3
        with:
          name: MossClient-Modlist
          path: build/mods.html