name: Build

on:
  push:
    branches-ignore:
        - master

jobs:
  build-mrpack:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      MOSS_ENABLED_MODULES: mrpack
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            .cache
          key: ${{ runner.os }}-packwiz
          restore-keys: |
            ${{ runner.os }}-packwiz
      - name: Build MrPack
        run: |
          chmod +x moss.sh
          ./moss.sh
      - name: Upload Build Results
        uses: actions/upload-artifact@v3
        with:
          name: MossClient-MrPack
          path: build/*.mrpack

  build-modlist:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      MOSS_ENABLED_MODULES: mlraw
    steps:
      - uses: actions/checkout@v3
      - name: Build Modlist
        run: |
         chmod +x moss.sh
         ./moss.sh
      - name: Upload Build Results
        uses: actions/upload-artifact@v3
        with:
          name: MossClient-Modlist
          path: |
            build/*.html
            build/*.txt